console.log("Welcome to the main module")
import { createPlan } from "./plan.js" //imports the createPlan fromt he plan.js file(module)
import { createWheat } from "./seeds/wheat.js"//imports the function to create wheat
import { createSunflower } from "./seeds/sunflower.js"//imports the function to create sunflowers
import { createSoybean } from "./seeds/soybean.js"//imports the function to create soybeans
import { createAsparagus } from "./seeds/asparagus.js"//imports the function to create asparagus
import { createPotato } from "./seeds/potato.js"//imports the function to create potato
import { createCorn } from "./seeds/corn.js"//imports the function to create corn
import { usePlants } from "./field.js"
import { plantSeeds } from "./tractor.js"
import { harvestPlants } from "./harvester.js"
import { catalog } from "./catalog.js"


let yearlyPlan = createPlan()// used for console logging and initializing the function
let wheatTest = createWheat()// used for console logging and initializing the function
let makeSun = createSunflower()// used for console logging and initializing the function
let potato = createPotato()// used for console logging and initializing the function
let corn = createCorn()// used for console logging and initializing the function
let asp = createAsparagus()// used for console logging and initializing the function
let soy = createSoybean()// used for console logging and initializing the function
// // console.log(makeSun)
// console.log(potato)
// console.log(corn)
// console.log(asp)
// console.log(soy)
let plants = usePlants(plantSeeds(createPlan()))// pass in the plan to the plant seeds function, iterates over the array,
// and creates seeds and imputs them into the addplant function,addplant adds them to the field array. 
//use plants takes that input and returns a copy of the field array.
console.log(plants)

let harvest = harvestPlants(usePlants())//pulls the copy of the field array, iterate over it, check if corn or not, output number of new seeds based on output of original planted item,
//if corn take only half and store this value as the harvest var.
// console.log(harvest)
let main = document.querySelector("main") //query index for the first element with the main selector

main.innerHTML = catalog(harvest) //sets the html to match the html string generated by the catalog function that takes the input of harvest.

